meetup/config/routes.rb
Rails.application.routes.draw do

  root 'page#welcome'
  get '/about' => 'page#about'

  resources :issues

  resources :comments, only: [:create]

  get 'signup' => 'users#signup', :as => 'signup'
  get 'login'  => 'users#login',  :as => 'login'
  delete 'logout' => 'users#logout', :as => 'logout'
  post 'create_login_session' => 'users#create_login_session'
  resources :users, only: [:create]

end

meetup/app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :issue
	belongs_to :user

	validates :content, presence: true
end

meetup/app/models/issue.rb
class Issue < ActiveRecord::Base
	belongs_to :user
	has_many :comments
end

meetup/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	has_many :issues
	has_many :comments

	before_create { generate_auth_token(:auth_token) }

	validates :username, :email, presence: true
	validates :username, :email, uniqueness: { case_sensitive: false }

	def gravatar
	  gravatar_id = Digest::MD5.hexdigest(self.email.downcase)
	  "http://gravatar.com/avatar/#{gravatar_id}.png?s=512&d=retro"
	end

	private
	def generate_auth_token(column)
		begin
		  	self[column] = SecureRandom.urlsafe_base64
		end while User.exists?(column => self[column])
	end


end

meetup/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find_by_auth_token!(cookies[:auth_token]) if cookies[:auth_token]
  end

  helper_method :current_user
end

meetup/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@comment = Comment.new(comment_params)
		@comment.save

		respond_to do |format|
			format.js
		end
	end

	private
	def comment_params
		params.require(:comment).permit(:issue_id, :user_id, :content)
	end
end

meetup/app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  def show
  	@issue = Issue.find(params[:id])
  	@comments = @issue.comments
  end

  def new
    if not current_user
      flash[:notice] = "请登陆后再发布活动！"
      redirect_to :root
      return
    else
      @issue = Issue.new
    end
  end

  def create
    issue = Issue.new(issue_params)
    issue.user_id = current_user.id
    issue.save

    flash[:notice] = "活动发布成功!"
    redirect_to :root
  end

  def edit
  	@issue = Issue.find(params[:id])

    if @issue.user.id != current_user.id
      flash[:notice] ="没有修改该活动的权限!"

      redirect_to @issue
    end
  end

  def update
  	issue = Issue.find(params[:id])
  	issue.update_attributes(issue_params)
  	redirect_to issue
  end

  def destroy
  	issue = Issue.find(params[:id])
  	issue.destroy
  	redirect_to :root
  end

	private
	def issue_params
	  params.require(:issue).permit(:title, :content)
	end
end

meetup/app/controllers/page_controller.rb
class PageController < ApplicationController
	def welcome
		@issues = Issue.all.reverse
	end

	def about

	end
end

meetup/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signup
  	@user = User.new
  end

  def create
  	@user = User.create(user_params)

  	if @user.save
	  	cookies[:auth_token] = @user.auth_token
	  	redirect_to :root
	else
		render :signup
	end

  end

  def create_login_session
  	user = User.find_by_username(params[:username])

  	if user && user.authenticate(params[:password])
  		if params[:remember_me]
  			cookies.permanent[:auth_token] = user.auth_token
  		else
  			cookies[:auth_token] = user.auth_token
  		end
  		flash[:notice] = "登陆成功！"
  		redirect_to :root
  	else
  		flash[:notice] = "用户名或密码错误，请重试!"
  		redirect_to :login
  	end
  end

  def logout
  	cookies.delete(:auth_token)
  	redirect_to :root
  end

  private
  def user_params
  	params.require(:user).permit!
  end
end

meetup/app/helpers/application_helper.rb
module ApplicationHelper

	class HTMLwithPygments < Redcarpet::Render::HTML
	  def block_code(code, language)
	    Pygments.highlight(code, lexer: language)
	  end
	end

	def markdown(text)
	  renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
	  options = {
	    autolink: true,
	    no_intra_emphasis: true,
	    fenced_code_blocks: true,
	    lax_html_blocks: true,
	    strikethrough: true,
	    superscript: true
	  }
	  Redcarpet::Markdown.new(renderer, options).render(text).html_safe if text != nil
	end
end

meetup/app/views/comments/create.js.erb
$(".replies").append("<%= j render(partial: 'shared/comment', locals: {comment: @comment}) %>");
$(".reply textarea").val('');

meetup/app/views/issues/_form.html.erb
<div class="new-issue-form-container clearfix">
  <div class="new-issue-form clearfix">
    <%= form_for issue do |f| %>
      <dl class="form">
        <dt><%= f.label :title %></dt>
        <dd><%= f.text_field :title %></dd>
      </dl>
      <dl class="form">
        <dt><%= f.label :content %></dt>
        <dd><%= f.text_area :content %></dd>
      </dl>
      <p><%= f.submit "发布新活动", :class => "submit-issue-button btn btn-primary" %></p>
    <% end %>
  </div>
</div>

meetup/app/views/issues/edit.html.erb
<%= render partial: "form", locals: { issue: @issue } %>

meetup/app/views/issues/new.html.erb
<%= render partial: "form", locals: { issue: @issue } %>

meetup/app/views/issues/show.html.erb
<div class="issue-heading">
    <div class="container">
        <%= @issue.title %>
        <% if current_user && current_user == @issue.user %>
          <%= link_to 'Destroy', issue_path(@issue), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %>
          <%= link_to 'edit', edit_issue_path(@issue), class: "btn btn-primary" %>
        <% end %>
    </div>
</div>
<div class="container">
    <div class="replies">
        <article class="reply clearfix">
            <div class="avatar">
                <%= image_tag @issue.user.gravatar, { class: "image-circle" } %>
            </div>
            <div class="body">
                <div class="heading">
                    <h5 class="name">
                        <%= link_to @issue.user.username, "#" %>
                    </h5>
                </div>
                <%= markdown @issue.content %>
            </div>
        </article>
        <% @comments.each do |comment| %>
          <%= render partial: 'shared/comment', locals: { comment: comment } %>
        <% end %>
    </div>

    <% if current_user %>
        <%= render partial: 'shared/comment_box', locals: { issue: @issue } %>
    <% else %>
        <%= link_to '请登陆后再评论', login_path %>
    <% end %>
</div>

meetup/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Meetup</title>
	<%= stylesheet_link_tag 'application', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body class="<%= params[:controller] + '-' + params[:action] %>">
	<div class="navbar clearfix">
	  <div class="container">
	    <%= link_to 'Meetup', root_path, {class: 'navbar-brand'} %>
	    <ul class="nav left">
	      <li><%= link_to t('navbar.about'), '/about' %></li>
	    </ul>
	    <ul class="nav right">
	    	<% if current_user %>
	    		<%= link_to current_user.username, '#' %>
	    		<%= link_to 'Logout', logout_path, method: "delete" %>
	    	<% else %>
		    	<li><%= link_to t('navbar.login'), login_path %></li>
		    	<li><%= link_to t('navbar.signup'), signup_path %></li>
	    	<% end %>
	    </ul>
	  </div>
	</div>

	<% if flash[:notice] %>
	<div class="notice">
		<%= flash[:notice] %>
	</div>
	<% end %>

	<div class="container">
		<%= yield %>
	</div>
	<div class="footer">
	  <div class="container">
	    footer
	  </div>
	</div>
	<script>
	  $('.home-banner').anystretch();

	  // 自动隐藏notice提示
	  var hideNotice = function(){
	      $(".notice").fadeOut("slow");
	  }
	  setTimeout(hideNotice, 4000);
	</script>
</body>
</html>

meetup/app/views/page/_issue_list.html.erb
<div class="issue-list">
    <% issues.each do |issue| %>
    <article class="issue clearfix">
        <div class="avatar">
            <%= link_to issue.user.username do %>
                <%= image_tag issue.user.gravatar %>
            <% end %>
        </div>
        <div class="body">
            <h5 class="title">
            <%= link_to issue.title, issue_path(issue) %>
            </h5>
            <a class="read-more" href="#">read</a>
            <span class="meta-data">
            <a href="/happypeter">happypeter</a>
            <%= time_ago_in_words(issue.created_at) %>前
            </span>
        </div>
        <div class="issue-comment-count">
            <div class="fa fa-comments icon-muted"></div>
            <%= link_to issue.comments.count, issue %>
        </div>
    </article>
    <% end %>
</div>

meetup/app/views/page/about.html.erb
<h2><%= t("navbar.about") %></h2>

meetup/app/views/page/welcome.html.erb
<div class="home-banner" data-stretch="<%= image_url 'home-banner.jpg' %>">
	<div class="banner-inner container clearfix">
	  <h1>It's Party Time!</h1>
	  <p class="subheading">到时聚聚，聊聊程序</p>
	  <div class="home-banner-links">
	    <%= link_to "发布新活动", "/issues/new", class: "banner-btn btn" %>
	  </div>
	</div>
</div>

<div class="issue-list-header">
  <div class="container clearfix">
    <h1 class="issue-list-heading">所有活动都在下面了...</h1>
  </div>
</div>

<div class="container clearfix">
  	<%= render partial: "issue_list", locals: { issues: @issues }%>
</div>

meetup/app/views/shared/_comment.html.erb
<div class="reply clearfix">
    <div class="avatar">
        <%= link_to '#' do %>
        <%= image_tag current_user.gravatar, class: 'image-circle' %>
        <% end %>
    </div>
    <div class="body">
        <div class="heading">
            <h5 class="name"><%= link_to comment.user.username, "#" %></h5>
            <span class="datetime">
            <%= time_ago_in_words comment.created_at %>前
            </span>
        </div>
        <%= markdown comment.content %>
    </div>
</div>

meetup/app/views/shared/_comment_box.html.erb
<article class="reply clearfix">
  <div class="avatar">
    <%= link_to "#" do %>
      <%= image_tag current_user.gravatar, class: "image-circle" %>
    <% end %>
  </div>
  <div class="body">
  <%= form_for(Comment.new(issue_id: issue.id, user_id: current_user.id), { method: :post, remote: true }) do |f| %>
    <%= f.hidden_field :issue_id %>
    <%= f.hidden_field :user_id %>
    <%= f.text_area(:content) %>
    <%= f.submit '提交评论 ( Ctrl + Enter )', class: 'btn btn-primary btn-submit' %>
  <% end %>
  </div>
</article>
<script>
   var exist_commenter = [];

   $('.reply .name a').each(function() {
      if($.inArray($(this).text(), exist_commenter) < 0) {
        exist_commenter.push($(this).text());
      }
   });

   $('textarea').atwho({ at: "@", 'data': exist_commenter });

   $(".reply textarea#comment_content").keydown(function(e) {
       if ((e.ctrlKey||e.metaKey) && e.keyCode == 13) {
         $(".reply input[type=submit]").click();
       }
     });
</script>

meetup/app/views/users/login.html.erb
<div class="login-form-container clearfix">
    <div class="login-form">
        <%= form_tag "/create_login_session" do %>
        <dl class="form">
            <dt>
            <%= label_tag "用户名" %>
            </dt>
            <dd>
            <%= text_field_tag :username, params[:username] %>
            </dd>
        </dl>
        <dl class="form">
            <dt>
            <%= label_tag "密码" %>
            </dt>
            <dd>
            <%= password_field_tag :password, params[:password] %>
            </dd>
        </dl>
        <dl class="form remember-me">
            <%= check_box_tag :remember_me, 1, params[:remember_me] -%>
            <%= label_tag :remember_me, t("login.remember_me") %>
        </dl>
        <p> <%= submit_tag "登录", :class => "login-button btn btn-primary" %> </p>
        <div class="need-signup">
            没有账号？<%= link_to "注册", signup_path %>一个吧
        </div>
        <% end %>
    </div>
</div>

meetup/app/views/users/signup.html.erb
<div class="signup-form-container clearfix">
    <div class="signup-form">
        <%= form_for @user do |f| %>
        <dl class="form">
            <dt><%= f.label :username, "用户名" %></dt>
            <dd><%= f.text_field :username %></dd>
            <% if @user.errors[:username].any? %>
              <dd class="error"><%= @user.errors[:username].join("<br/>") %></dd>
            <% end %>
        </dl>
        <dl class="form">
            <dt><%= f.label :email, "邮箱地址" %></dt>
            <dd><%= f.text_field :email %></dd>
            <% if @user.errors[:email].any? %>
              <dd class="error"><%= @user.errors[:email].join("<br/>") %></dd>
            <% end %>
        </dl>
        <dl class="form">
            <dt><%= f.label :password, "密码" %></dt>
            <dd><%= f.password_field :password %></dd>
            <% if @user.errors[:password].any? %>
              <dd class="error"><%= @user.errors[:password].join("<br/>") %></dd>
            <% end %>
        </dl>
        <dl class="form">
            <dt><%= f.label :password_confirmation, "请再输入一次" %></dt>
            <dd><%= f.password_field :password_confirmation %></dd>
            <% if @user.errors[:password_confirmation].any? %>
              <dd class="error"><%= @user.errors[:password_confirmation].join("<br/>") %></dd>
            <% end %>
        </dl>
        <p><%= f.submit "注册", :class => "signup-button btn btn-primary" %></p>
        <div class="need-signup">
        已账号？请直接<%= link_to "登陆", login_path %>
      </div>
        <% end %>
    </div>
</div>